[target.aarch64-linux-android]
linker = "/home/o/Android/Sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android28-clang"
rustflags = ["-C", "link-arg=-Wl,-z,max-page-size=16384"]

[env]
CC_aarch64-linux-android = "/home/o/Android/Sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android28-clang"
AR_aarch64-linux-android = "/home/o/Android/Sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
CFLAGS_aarch64-linux-android = "-target aarch64-linux-android28"
